# Generated by Django 4.2.6 on 2024-01-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fapp1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, null=True)),
                ('pimage', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('price', models.PositiveIntegerField(null=True)),
                ('description', models.CharField(max_length=40, null=True)),
                ('qty', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
