# Generated by Django 4.2.6 on 2024-01-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp1', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, null=True)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('order_date', models.DateField(auto_now_add=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Order Confirmed', 'Order Confirmed'), ('In Transist', 'In Transist'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered')], max_length=50, null=True)),
                ('tracking_id', models.CharField(max_length=255, null=True)),
                ('is_receive', models.CharField(max_length=255, null=True)),
                ('is_delivered', models.BooleanField(default=False)),
                ('place', models.CharField(max_length=50, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapp1.client')),
                ('deliveryboy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapp1.delivery')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapp1.product')),
            ],
        ),
    ]
