# Generated by Django 4.2.6 on 2024-01-02 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fapp1', '0003_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliverymethod',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='noofitems',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapp1.client')),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fapp1.product')),
            ],
        ),
    ]
